---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: wp-pv-volume
  labels:
    type: azure-files
---
template:
  volumes:
  - name: wordpress-share
    storageName: pidaymount
  containers:
  - image: wordpress:6.0.1-php7.4
    name: wordpress
    volumeMounts:
    - volumeName: piday28627
      mountPath: /var/www/html
    resources:
      cpu: 0.5
      ephemeralStorage: 3Gi
      memory: 1Gi
  initContainers: null
  revisionSuffix: ''
  scale:
    maxReplicas: 1
    minReplicas: 1
    rules: null
